//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewelly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemMst()
        {
            this.DimMsts = new HashSet<DimMst>();
            this.Orderdetails = new HashSet<Orderdetail>();
            this.StoneMsts = new HashSet<StoneMst>();
        }
    
        public int Style_Code { get; set; }
        public decimal Pairs { get; set; }
        public decimal Quantity { get; set; }
        public string Prod_Quality { get; set; }
        public decimal Gold_Wt { get; set; }
        public decimal Stone_Wt { get; set; }
        public decimal Net_Gold { get; set; }
        public decimal Wstg_Per { get; set; }
        public decimal Wstg { get; set; }
        public decimal Tot_Gross_Wt { get; set; }
        public decimal Gold_Rate { get; set; }
        public decimal Gold_Amt { get; set; }
        public decimal Gold_Making { get; set; }
        public decimal Stone_Making { get; set; }
        public decimal Other_Making { get; set; }
        public decimal Tot_Making { get; set; }
        public decimal MRP { get; set; }
        public Nullable<int> Img_ID { get; set; }
        public Nullable<int> Brand_ID { get; set; }
        public Nullable<int> Cat_ID { get; set; }
        public Nullable<int> Certify_ID { get; set; }
        public Nullable<int> Prod_ID { get; set; }
        public Nullable<int> GoldType_ID { get; set; }
        public Nullable<int> DimID { get; set; }
        public Nullable<int> ID_jewelly { get; set; }
    
        public virtual BrandMst BrandMst { get; set; }
        public virtual CatMst CatMst { get; set; }
        public virtual CertifyMst CertifyMst { get; set; }
        public virtual DimInfoMst DimInfoMst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimMst> DimMsts { get; set; }
        public virtual GoldKrtMst GoldKrtMst { get; set; }
        public virtual Img Img { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderdetail> Orderdetails { get; set; }
        public virtual JewelTypeMst JewelTypeMst { get; set; }
        public virtual ProdMst ProdMst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoneMst> StoneMsts { get; set; }
    }
}
